// Use import.meta.glob to import all images matching the pattern.
// This will create an object where keys are paths like './src/assets/thumbnails/...'
// and values are the public URLs of the assets.
const allImages = import.meta.glob(
  "../src/assets/thumbnails/**/*.{jpg,jpeg,png,gif}",
  { eager: true, as: "url" }
);

/**
 * Transforms a JSON path (e.g., './assets/thumbnails/movie/regular/small.jpg')
 * into the actual public URL generated by Vite.
 *
 * @param {string} jsonPath The path string from your JSON data.
 * @returns {string} The public URL of the image, or an empty string if not found.
 */
export function getImageUrl(jsonPath) {
  // Your JSON paths start with './assets/'.
  // The keys in 'allImages' (from import.meta.glob) start with './src/assets/'.
  // We need to transform the JSON path to match the glob key.
  // Example: './assets/thumbnails/beyond-earth/trending/small.jpg'
  const viteGlobKey = `./src/${jsonPath.substring(2)}`; // Remove './' and prepend './src/'

  console.log(allImages);

  // Return the URL if found, otherwise an empty string or a placeholder
  return allImages[viteGlobKey] || "";
}

// You could also export the allImages object directly if needed for debugging
// export { allImages };
